title: "Words"
description: "It's really me!"
date_format: "%b %-d, %Y"
lang: "en"
markdown: kramdown
highlighter: rouge
exclude:
  - styles
keep_files:
  - styles
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
